name: text2mol_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8
  - numpy=1.23.5
  - pandas=2.0.3
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - flask=3.1.0
  - pymysql=1.1.1
  - matplotlib=3.7.1
  - seaborn
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - ipython=8.15.0
  - networkx=3.2.1
  - tqdm=4.67.1
  - transformers=4.49.0
  - pip=25.1
  - pip:
    - torch-cluster==1.6.1+pt20cu118
    - torch-scatter==2.1.1+pt20cu118
    - torch-sparse==0.6.17+pt20cu118
    - torch-geometric==2.4.0
    - sentence-transformers
    - nltk
    - joblib=1.4.2
    - requests=2.28.2
    - beautifulsoup4=4.12.3
    - PyYAML=6.0.2
    - python-dateutil=2.9.0.post0
    - regex=2024.11.6
    - safetensors=0.5.3
    - tokenizers=0.21.0
    - huggingface-hub=0.29.2
    - datasets=2.12.0 